# Generated by Django 5.0 on 2023-12-28 16:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_area', models.CharField(choices=[('arm', '腕'), ('back', '背中'), ('chest', '胸'), ('leg', '脚'), ('abdominal', '腹')], max_length=64, verbose_name='トレーニング部位')),
            ],
            options={
                'verbose_name': 'トレーニング部位',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=64, verbose_name='トレーニング種目')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trainingarea')),
            ],
            options={
                'verbose_name': 'トレーニング種目',
            },
        ),
    ]
