# Generated by Django 5.0 on 2023-12-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutitem',
            name='category',
        ),
        migrations.AddField(
            model_name='workoutitem',
            name='category',
            field=models.ManyToManyField(to='workout.trainingarea'),
        ),
    ]
