# Generated by Django 5.0 on 2024-01-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingarea',
            name='training_area',
            field=models.CharField(choices=[('arm', '腕'), ('back', '背中'), ('chest', '胸'), ('leg', '脚'), ('shoulder', '肩'), ('abdominal', '腹')], max_length=64, verbose_name='トレーニング部位'),
        ),
    ]
